# Dockerfile to make it easy running TensorFlow via Nvidia docker on EC2 g2 instance.

FROM ubuntu:16.04

MAINTAINER sergei <sergei.0910@gmail.com>

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        build-essential \
        curl \
        vim \
        git \
        net-tools \
        iputils-ping \
        netcat \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python \
        python-dev \
        python-numpy \
        python-wheel \
        python-mock \
        rsync \
        zip \
        unzip \
        g++ \
        zlib1g-dev \
        golang \
        fuse \
        rsyslog \
        && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip --no-cache-dir install \
        ipykernel \
        jupyter \
        matplotlib \
        scipy \
        sklearn \
        pandas \
        Pillow \
        h5py \
        sgf \
        futures \
        keras \
        awscli \
        && \
    python -m ipykernel.kernelspec

WORKDIR /root

# Install Tensorflow 
RUN pip --no-cache-dir install \
    http://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp27-none-linux_x86_64.whl

# Install goofys
RUN export GOPATH=/root/go && \
    go get -v github.com/kahing/goofys && \
    go install -v github.com/kahing/goofys

# Copy AWS credentials
RUN  mkdir /root/.aws
COPY credentials /root/.aws/credentials

# We just add a little wrapper script.
COPY bootstrap.sh /

# TensorBoard
EXPOSE 6006

CMD ["/bootstrap.sh"]
